---
title: 'Pandoc: your Swiss army knife'
publisher: 'Programming Language Fight Club'
author: Kiko Fernandez-Reyes
rights: 2018 Kiko Fernandez-Reyes, CC BY-SA 4.0 International
cover-image: assets/pandoc.jpg
stylesheet: assets/epub.css
toc-depth: 2
...